AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  app-sync-backend

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    MemorySize: 256
    CodeUri: backend
    Architectures:
      - x86_64
    Runtime: nodejs18.x

Resources:
##########################################################################
#                              S3 Bucket                                 #
##########################################################################
  S3:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
##########################################################################
#                              Dynamo Table                              #
########################################################################## 
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
##########################################################################
#                              GraphQL AppSync                          #
##########################################################################     
  GQL:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      ApiKeys:
        MyApiKey:
          Description: "My API Key"
      Auth:
        Type: API_KEY
      SchemaUri: ./backend/src/graphql/schema.graphql
      DataSources:
        DynamoDb:
          TableDataSource:
            TableName: !Ref Table
            TableArn: !GetAtt Table.Arn
        Lambda:
          ApiProxyDataSource:
            FunctionArn: !GetAtt ApiProxyFunction.Arn
      Functions:
        createStory:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: TableDataSource
          CodeUri: ./backend/src/graphql/resolvers/js/create-story.resolver.js
        getStory:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: TableDataSource
          CodeUri: ./backend/src/graphql/resolvers/js/get-story.resolver.js
        apiProxy:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: ApiProxyDataSource
          CodeUri: ./backend/src/graphql/resolvers/js/api-proxy.resolver.js
      Resolvers:
        Mutation:
          createStory:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - createStory
        Query:
          getStory:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - getStory
          getCoffeePhotoUrl:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - apiProxy
##########################################################################
#                           Lambda Functions                             #
##########################################################################
  ApiProxyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: backend/
      Handler: api-proxy.apiProxyHandler
      Environment:
        Variables:
          DATABASE_NAME:
            Ref: Table
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - src/lambdas/api-proxy.ts
         
##########################################################################
#                           Outputs                                      #
##########################################################################
Outputs:
  AppSyncApiId:
    Description: AppSync API Key
    Value: !GetAtt GQLMyApiKey.ApiKey
  AppSyncGraphQLUrl:
    Description: "AppSync GraphQL URL"
    Value: !GetAtt GQL.GraphQLUrl
