AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  app-sync-backend

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    MemorySize: 256
    CodeUri: backend
    Architectures:
      - x86_64
    Runtime: nodejs18.x

Resources:
##########################################################################
#                              S3 Bucket                                 #
##########################################################################
  S3:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
##########################################################################
#                              Dynamo Table                              #
########################################################################## 
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: title
          AttributeType: S
        - AttributeName: content
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
##########################################################################
#                              GraphQL AppSync                          #
##########################################################################     
  GQL:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      ApiKeys:
        MyApiKey:
          Description: "My API Key"
      Auth:
        Type: API_KEY
      SchemaUri: ./graphql/schema.graphql
      DataSources:
        DynamoDb:
          TableDataSource:
            TableName: !Ref Table
            TableArn: !GetAtt Table.Arn
        Lambda:
          ExportStoriesDataSource:
            FunctionArn: !GetAtt ExportStoriesToCsvFunction.Arn
      Functions:
        createStory:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: TableDataSource
          CodeUri: ./src/grapql/resolvers/js/create-story.resolver.js
        getStory:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: TableDataSource
          CodeUri: ./src/grapql/resolvers/js/get-story.resolver.js
        exportStoriesToCsv:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: ExportStoriesDataSource
          CodeUri: ./src/grapql/resolvers/js/export-stories-to-csv.resolver.js
      Resolvers:
        Mutation:
          createPost:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - createStory
        Query:
          getStory:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - getStory
          exportStoriesToCsv:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - exportStoriesToCsv
  PostApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
##########################################################################
#                           Lambda Functions                             #
##########################################################################
  ExportStoriesToCsvFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: backend/
      Handler: export-stories-to-csv.handler
      Environment:
        Variables:
          BUCKET_NAME:
            Ref: S3
          DATABASE_NAME:
            Ref: Table
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table
        - S3ReadPolicy:
            BucketName: !Ref S3
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - src/lambdas/export-stories-to-csv.ts
        External:
          - '@aws-sdk/client-s3'
          - '@aws-sdk/s3-request-presigner'
          - '@aws-sdk/client-dynamodb'
##########################################################################
#                           Outputs                                      #
##########################################################################
Outputs:
  AppSyncApiId:
    Description: "AppSync GraphQL API ID"
    Value: !GetAtt GQL.ApiId
  AppSyncGraphQLUrl:
    Description: "AppSync GraphQL URL"
    Value: !GetAtt GQL.GraphQLUrl
